#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🔍 Running lint-staged..."
npx lint-staged

echo "🧠 Running typecheck..."
npm run typecheck || exit 1

echo "🧪 Running tests with coverage..."
npm run test:coverage || exit 1